import os
import csv
from datetime import datetime

def is_noise(file_path):
    '''
    Filters out noisy lines using simple string matching instead of regex.
    Returns True if the line should be skipped.
    '''
    # Using simple lowercase string matching to avoid any regex/backslash parsing issues
    path_lower = file_path.lower()
    
    # We use simple substring checks natively
    if '$file_name' in path_lower or '$file_name' in file_path:
        return True
    if 'winsxs' in path_lower:
        return True
    if 'servicing/packages' in path_lower.replace('\\', '/'):
        return True
    if 'microsoft/windows/caches' in path_lower.replace('\\', '/'):
        return True
        
    return False

def parse_body_file(body_file_path, output_csv_path, update_ui_func=None):
    '''
    Reads a .body file generated by MFTECmd, converts UNIX timestamps to UTC dates,
    applies filters natively (replacing grep/sed), and exports to CSV.
    '''
    if not os.path.exists(body_file_path):
        return False, f'Error: file {body_file_path} not found.'
    
    headers = ['Date', 'Size', 'Type', 'Mode', 'UID', 'GID', 'Meta', 'File Name']
    written_rows = 0
    
    try:
        if update_ui_func:
            update_ui_func('Starting native mactime parsing...')
            
        with open(body_file_path, 'r', encoding='utf-8', errors='replace') as infile, \
             open(output_csv_path, 'w', encoding='utf-8', newline='') as outfile:
                 
            writer = csv.writer(outfile, lineterminator='\n')
            writer.writerow(headers)
            
            for line in infile:
                parts = line.strip().split('|')
                
                if len(parts) >= 11:
                    name = parts[1]
                    name = name.replace('/', '\\\\')
                    
                    if is_noise(name):
                        continue
                    
                    inode = parts[2]
                    mode = parts[3]
                    uid = parts[4]
                    gid = parts[5]
                    size = parts[6]
                    
                    # Track mtime (Modification)
                    mtime_unix = int(parts[8]) if parts[8].isdigit() else 0
                    
                    if mtime_unix > 0:
                        try:
                            date_str = datetime.utcfromtimestamp(mtime_unix).strftime('%Y-%m-%d %H:%M:%S')
                        except:
                            date_str = 'UNKNOWN'
                    else:
                        date_str = 'UNKNOWN'
                    
                    row = [date_str, size, 'mtime', mode, uid, gid, inode, name]
                    writer.writerow(row)
                    written_rows += 1
                    
        if update_ui_func:
            update_ui_func(f'Success: Wrote {written_rows} rows to {output_csv_path}')
        return True, f'Successfully parsed {written_rows} lines to {output_csv_path}'
        
    except Exception as e:
        if update_ui_func:
            update_ui_func(f'Error during parsing: {str(e)}')
        return False, f'Exception during parsing: {str(e)}'
